In [ ]:
import numpy as np
LX = 64
LS = 128
OV = 0,5
data = np.linspace(10,30, 1024)
k = 0
cont = 0
x = data



In [ ]:
indices = []

k=0
while True:
    indice = np.array(x[int((LX/2)*k):int((LX/2)*k + LX)])
    indices = np.append(indice,indices)
    #values = indices[k]
    #values = np.asmatrix(values)
    #values = value
    #print(indices)
    k = k+1
    lent= (len(data)-LX/2)
    if len(indices) > lent :
        break
print(indices)

[19.38416422 19.40371457 19.42326491 ... 11.19257087 11.21212121
 11.23167155]


In [ ]:
values = indices.reshape(k, 64)
print(values)

[[19.38416422 19.40371457 19.42326491 ... 20.57673509 20.59628543
  20.61583578]
 [18.75855327 18.77810362 18.79765396 ... 19.95112414 19.97067449
  19.99022483]
 [18.13294233 18.15249267 18.17204301 ... 19.3255132  19.34506354
  19.36461388]
 ...
 [11.2512219  11.27077224 11.29032258 ... 12.44379277 12.46334311
  12.48289345]
 [10.62561095 10.64516129 10.66471163 ... 11.81818182 11.83773216
  11.8572825 ]
 [10.         10.01955034 10.03910068 ... 11.19257087 11.21212121
  11.23167155]]


In [ ]:
sz1 = values.shape[0]
numseg = sz1
print(numseg)

16


In [ ]:
x1=np.array([])
x2= np.array([])
o = x.shape
w = np.zeros(o[0])
Bsp=np.zeros((LX,LX))
de1=np.zeros((LX,LX))
de2=np.zeros((LX,LX))
D1 = np.array([])
D2 = np.array([])
Bs = np.array([])
for ix in range(0,numseg) :
    mui = np.mean(values[ix])
    a = values[ix]-mui
    x1 = np.append(x1,a)
    #hanning window
    for k in range(0,len(x1)):
        w[k]= 0.5 - 0.5*np.cos(2*np.pi*(k-1)/(LX-1))

    for k in range (0,len(x1)):
        abc = w[k]*x1[k]
        x2 = np.append(x2,abc)
    
    Y= np.fft.fft(np.array(x2),LS)
    for k in range(0,LX):
        for l in range(0,LX):
            Bsp[k,l]= Y[k]*Y[l]*np.conjugate(Y[k+l])
            de1[k,l]=abs(Y[k]*Y[l])**2
            de2[k,l]=abs(Y[k+l])**2
    Bs=np.append(Bs,Bsp)
    D1=np.append(D1,de1)
    D2=np.append(D2,de2)
 


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: ComplexWarning: Casting complex values to real discards the imaginary part


In [ ]:
D1= D1.reshape(16,64,64)
D2 = D2.reshape(16,64,64)
Bs = Bs.reshape(16,64,64)


In [ ]:
D1m = D1[0]
D1m.shape

(64, 64)

In [ ]:
#menghitung bisepectrum dan bicoherence

D1m = D1[0]
D2m = D2[0]
Bm = Bs[0]
sz2= Bs.shape[0]
for k in range(0,sz2):
    D1m=D1m+D1[k]
    D2m=D2m+D2[k]
    Bm = Bm+Bs[k]
D1 = D1m/k
D2 = D2m/k
Bm = Bm/k
#print(Bm)

In [ ]:
bic2 = np.zeros((LX*2,LX*2))
for k in range(0,LX):
    for l in range(0,LX):
        bic2[k+LX,l+LX] = abs(Bm[k,l])**2 / (D1[k,l]*D2[k,l])



In [ ]:
bican = np.zeros((LX*2,LX*2))
for k in range(0,LX*2):
    for l in range(0,LX*2):
        if (k<=LX) and (l<=LX):
            bican[k,l] = bic2[(2*LX-k-1),(2*LX-l-1)]
        elif (k>LX) and (l<=LX):
            bican[k,l]=bic2[k,2*LX-l-1]

        elif (k<=LX) and (l>LX):
            bican[k,l]=bic2[2*LX-k-1,l]
            
        elif (k<LX) and (l>bic2[k,l]):
            bican[k,l] = bic2[k,l]
        

In [ ]:
print(bican)

[[8.56794122e-07 9.97430755e-01 6.72811179e-04 ... 6.72811179e-04
  9.97430755e-01 8.56794122e-07]
 [9.97430755e-01 8.75806837e-03 9.96660129e-01 ... 9.96660129e-01
  8.75806837e-03 9.97430755e-01]
 [6.72811179e-04 9.96660129e-01 1.54595877e-03 ... 1.54595877e-03
  9.96660129e-01 6.72811179e-04]
 ...
 [6.72811179e-04 9.96660129e-01 1.54595877e-03 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [9.97430755e-01 8.75806837e-03 9.96660129e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [8.56794122e-07 9.97430755e-01 6.72811179e-04 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [ ]:
#mengambil nilai bican yang berelemen 0
bicanpl = bican
bican1=bican[LX:int(LX+LS/2),LX:int(LX+LS/2)]
sz0=bican1.shape
print(bican1)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
waxis = np.linspace(0,0.5,sz[1]+1)
waxis = waxis[:-2]

limit =waxis[-1]*(2/3)


In [ ]:
k = 0
while k<len(waxis):
    if waxis[k] > limit :
        limit = k-1
        k=float('inf')
    else :
        k = k+1
        

In [ ]:
for f1 in range(0,limit):
    for f2 in range(0,len(waxis)):
        if f2 == 0 or f2>= f1:
            bican[f1,f2] = 0
          

In [ ]:
print(bican)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 6.72811179e-04
  9.97430755e-01 8.56794122e-07]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 9.96660129e-01
  8.75806837e-03 9.97430755e-01]
 [0.00000000e+00 9.96660129e-01 0.00000000e+00 ... 1.54595877e-03
  9.96660129e-01 6.72811179e-04]
 ...
 [6.72811179e-04 9.96660129e-01 1.54595877e-03 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [9.97430755e-01 8.75806837e-03 9.96660129e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [8.56794122e-07 9.97430755e-01 6.72811179e-04 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [ ]:
bican[1,2]

0.0

In [ ]:
bicpermed = np.array([])
cont = 0
for f1 in range(0,len(waxis)):
    for f2 in range(0, min([f1, -2*f1+len(Y)])):
        bicp =  bican[f1,f2]
        cont = cont +1
        bicpermed=np.append(bicpermed,bicp)
        


In [ ]:
print(bicpermed)
len(bicpermed)

[0.         0.         0.99666013 ... 0.9806081  0.0320039  0.9728685 ]


1363

In [ ]:
bic2m = np.mean(bicpermed)
bic2v=np.std(bicpermed)
bic2max = max(bicpermed)
print(bic2m)

0.478482267261243


In [ ]:
#NILAI KETIDAKLINEARAN
NLI = abs(bic2max-(bic2m+(2*bic2v)))
print(NLI)

0.2450193763527575


In [ ]:
size,size2 = bican.shape

In [ ]:
b = np.transpose(bican)
rows = []
for ix in range(0,size):
    c = np.max(bican[ix])
    rows = np.append(rows,c)



0.9988903690381101

In [ ]:
f1 = rows[0]
f2 = rows[1]
print(f1)
print(f2)

0.9999999999999998
0.9988903690381101


In [ ]:
#Mengitung NGI
al = 0.01
chi = 9.2
chi2 = chi/(2*LX)

xi,xii = np.where(bican[:]>chi2)
b=xi+xii
c=sum(b)
n=len(xi)
biccrit = (1/(4*LX*n))*((chi+np.sqrt((4*n)-1))**2)
NGI = bic2m-biccrit
print(NGI)

0.4609498254462119


In [ ]:
import matplotlib.pyplot as plt